### ISSUE TITLE
Only graph is shown

### ISSUE THREAD

**Issue by Kim-Seonghyeon** [lspvic/jupyter_tensorboard#13]
jupyter-tensorboard (0.1.5)
tensorboard (1.6.0)
tensorboard-pytorch (0.7.1)
tensorflow (1.3.0)
tensorflow-gpu (1.4.0)
tensorflow-tensorboard (0.4.0)

Scalars are shown with standalone tensorboard but not with jupyter tensorboard.
Is there any problem with version of my packages?
In chrome console there is plugin_list file.

-(plugin_list)
{distributions: false, images: false, profile: false, scalars: false, text: false, audio: false,…}
audio
:
false
core
:
true
distributions
:
false
graphs
:
true
histograms
:
false
images
:
false
profile
:
false
projector
:
false
scalars
:
false
text
:
false

**Comment by Kim-Seonghyeon** [comment]
And below is plugin_list file with standalone tensorboard.

{profile: false, scalars: true, distributions: false, custom_scalars: false, images: false,…}
audio:false
core:true
custom_scalars:false
distributions:false
graphs:true
histograms:false
images:false
pr_curves:false
profile:false
projector:false
scalars:true
text:false

**Comment by Kim-Seonghyeon** [comment]
OMG sorry. It works after restart jupyter. Finally..

**Comment by helmetti** [comment]
I strongly recommend you to confirm 10 times before you report something. Thanks
