### ISSUE TITLE
This bypasses JupyterHub security

### ISSUE THREAD

**Issue by elgalu** [lspvic/jupyter_tensorboard#15]
#### Security

I tried today and in a JupyterHub installation I could access the Tensor Board in incognito window meaning it bypasses JupyterHub auth.

**Comment by lspvic** [comment]
Thanks for your feedback. I will check and fix it soon.

**Comment by lspvic** [comment]
The new version 0.1.6 has solved this security issue.
Please update via
`pip install -U jupyter-tensorboard`

**Comment by elgalu** [comment]
Works!! thanks for fixing this so fast!!
