### ISSUE TITLE
Only graphs shown

### ISSUE THREAD

**Issue by 2sin18** [lspvic/jupyter_tensorboard#2]
Scalars, images and anything except graphs are missing. We need a full functioned plugin.

**Comment by lspvic** [comment]
Have you try in a tensorboard command line and check whether others are showed or not?
or can you give some more information? such as tensorboard's version and network inspect in chrome as below
![tim 20170828143550](https://user-images.githubusercontent.com/4335658/29761911-455d7812-8bfe-11e7-8301-afb015dfcd68.png)

As this extension only forward tensorboard's content, I can't figure why only graph is displayed.

**Comment by 2sin18** [comment]
Thanks for your attention.

I tried demo case in https://www.tensorflow.org/get_started/summaries_and_tensorboard, standalone tensorboard works nicely, but jupyter-tensorboard only shows graphs.

In network inspect in chrome, I found plugins_listing only have graphs enabled:

```
{profile: false, core: true, projector: false, scalars: false, text: false, histograms: false,…}
audio
:
false
core
:
true
distributions
:
false
graphs
:
true
histograms
:
false
images
:
false
profile
:
false
projector
:
false
scalars
:
false
text
:
false
```

**Comment by 2sin18** [comment]
Finally I find out where the problem lies: I use tensorflow 1.2.1 and this plugin only support tensorflow>=1.3. 

Thanks again and could you explain the reason why this plugin is related to tensorflow version? This plugin just forwards request to tensorboard, so it should be irrelevant to tensorflow.

**Comment by lspvic** [comment]
Tensorboard is seperated from tensorflow from version 1.2. However, tensorflow 1.2 still contains tensorboard in it's directory. This jupyter_tensorboard uses the seperated version, i.e, tensorflow-tensorboard package, via `from tensorboard import application`. I think in your standalone tensorboard, it used the version of tensorboard inside tensorflow. If you run `cat $(which tensorboard)`, you will find `from tensorflow.tensorboard.main import main`. The two versions might be different.  tensorflow/tensorboard#404 point out the problem and suggest to upgrade to tensorflow 1.3.

Tensorflow 1.3 doesn't contain tensorboard inside its directory and depends on tensorflow-tensorboard package. Although it's possible to support tensorflow 1.1 and 1.2 for this extension, the tensorboard codes in these versions varies a lot and there need to specified codes for different version to support, so I don't plan to support these versions.

Very thanks for all your feedback.
