### ISSUE TITLE
Jupyter option 'c.ContentsManager.root_dir' causing wrong logdir path

### ISSUE THREAD

**Issue by dave992** [lspvic/jupyter_tensorboard#23]
The jupyter option 'c.ContentsManager.root_dir' is a convenient way for me to start the server in a specific folder from a new terminal. This is due to running the server remotely and often starting it via SSH. For this purpose lets say I use the following option:
c.ContentsManager.root_dir = '/home/\<user>/JupyterServer'

If I use this plugin to start a TensorBoard instance, it starts normally but is unable to find the event files in the selected folder.  Inside the root_dir  (= '/home/\<user>/JupyterServer/') I have the following basic structure:
```
project1/
│   main.py 
└───logs/
     └───tensorboard/
         │   ...
         │   ...
```
To start the instance I select the tensorboard folder, and click the TensorBoard button. When I open the TensorBoard page it shows the warning: `No dashboards are active for the current data set.` This page also shows the location it got provided to start the instance: `Data location: /home/<user>/project1/logs/tensorboard` which is incorrect and does not take the root_dir into account. Instead it should have been: `Data location: /home/<user>/JupyterServer/project1/logs/tensorboard`

I did notice that in the Running tab, the TensorBoard process is shown with the following dir: `<notebook_dir>/project1/logs/tensorboard`. I suppose the notebook_dir is the location where the server is started in. However, the tree view of the notebook starts in the root_dir location, which is different in my use case. 

As a temporary solution, is it possible to start a new TensorBoard instance from the Notebook itself by providing the path manually?

**Comment by lspvic** [comment]
New version 0.1.7 has fixed the problem. Have a try~

**Comment by dave992** [comment]
Thanks for the reply and fast fix.
