### ISSUE TITLE
TF 1.4.0rc is not supported.

### ISSUE THREAD

**Issue by shiquanwang** [lspvic/jupyter_tensorboard#3]
I installed jupyter_tensorboard with TF1.4.0rc.
It's not supported.

**Comment by lspvic** [comment]
jupyter-tensorflow v0.1.4.dev0 which support tensorflow 1.4.0rc has been uploaded to pypi.  Please upgrade via
```
pip install --pre -U jupyter-tensorflow
```

**Comment by shiquanwang** [comment]
Thanks. It works.
