### ISSUE TITLE
Works with tensorflow version 1.10 but not 1.11

### ISSUE THREAD

**Issue by alexgadam** [lspvic/jupyter_tensorboard#31]
Jupyter-tensorboard fails to launch with tensorflow version 1.11 (you get a Jupyter-tensorboard extension error - the Javascript console simply outputs - Failed to load resource: the server responded with a status of 500). Downgrading to version 1.10 fixes the issue. 

This issue happens for both the CPU and GPU installations of tensorflow 1.11

**Comment by fqzhou** [comment]
It's really the case. I have the same issues. Thank you for sharing this message.

**Comment by tranhungnghiep** [comment]
Can confirm. Downgrade tf to 1.10 works, 1.11 fails. Please look into this issue.
