### ISSUE TITLE
Uncaught exception POST /api/tensorboard (127.0.0.1)

### ISSUE THREAD

**Issue by tzom** [lspvic/jupyter_tensorboard#34]
I get an exception when trying to use jupyter-tensorboard (although tensorboard itself runs and is accessible from the chrome browser):

> [E 15:01:59.247 NotebookApp] 500 POST /api/tensorboard (127.0.0.1) 8.61ms referer=http://localhost:8080/tree?
[E 15:02:15.460 NotebookApp] Uncaught exception POST /api/tensorboard (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8080', method='POST', uri='/api/tensorboard', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/altenburgt/pkgs/anaconda3/envs/tensorflow-cpu/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/altenburgt/pkgs/anaconda3/envs/tensorflow-cpu/lib/python3.6/site-packages/tornado/web.py", line 3006, in wrapper
        return method(self, *args, **kwargs)
      File "/home/altenburgt/pkgs/anaconda3/envs/tensorflow-cpu/lib/python3.6/site-packages/jupyter_tensorboard/api_handlers.py", line 36, in post
        .new_instance(data["logdir"], reload_interval=reload_interval)
      File "/home/altenburgt/pkgs/anaconda3/envs/tensorflow-cpu/lib/python3.6/site-packages/jupyter_tensorboard/tensorboard_manager.py", line 137, in new_instance
        purge_orphaned_data=purge_orphaned_data)
      File "/home/altenburgt/pkgs/anaconda3/envs/tensorflow-cpu/lib/python3.6/site-packages/jupyter_tensorboard/tensorboard_manager.py", line 35, in create_tb_app
        tensorboard.assets_zip_provider)
      File "/home/altenburgt/pkgs/anaconda3/envs/tensorflow-cpu/lib/python3.6/site-packages/tensorboard/backend/application.py", line 158, in standard_tensorboard_wsgi
        reload_task)
    TypeError: TensorBoardWSGIApp() takes from 4 to 5 positional arguments but 6 were given

my conda list is:

>  Name                    Version                   Build  Channel
> _tflow_select             2.3.0                       mkl  
> absl-py                   0.6.1                    py36_0  
> astor                     0.7.1                    py36_0  
> backcall                  0.1.0                    py36_0  
> backcall                  0.1.0                     <pip>
> blas                      1.0                         mkl  
> bleach                    3.0.2                     <pip>
> bleach                    3.0.2                    py36_0  
> c-ares                    1.15.0               h7b6447c_1  
> ca-certificates           2018.03.07                    0  
> certifi                   2018.10.15               py36_0  
> cycler                    0.10.0                   py36_0  
> dbus                      1.13.2               h714fa37_1  
> decorator                 4.3.0                     <pip>
> decorator                 4.3.0                    py36_0  
> defusedxml                0.5.0                     <pip>
> entrypoints               0.2.3                     <pip>
> entrypoints               0.2.3                    py36_2  
> expat                     2.2.6                he6710b0_0  
> fontconfig                2.13.0               h9420a91_0  
> freetype                  2.9.1                h8a8886c_1  
> gast                      0.2.0                    py36_0  
> glib                      2.56.2               hd408876_0  
> gmp                       6.1.2                h6c8ec71_1  
> grpcio                    1.14.1           py36h9ba97e2_0  
> gst-plugins-base          1.14.0               hbbd80ab_1  
> gstreamer                 1.14.0               hb453b48_1  
> h5py                      2.8.0            py36h989c5e5_3  
> hdf5                      1.10.2               hba1933b_1  
> icu                       58.2                 h9c2bf20_1  
> intel-openmp              2019.1                      144  
> ipykernel                 5.1.0            py36h39e3cac_0  
> ipython                   7.1.1            py36h39e3cac_0  
> ipython-genutils          0.2.0                     <pip>
> ipython_genutils          0.2.0                    py36_0  
> jedi                      0.13.1                   py36_0  
> jedi                      0.13.1                    <pip>
> jinja2                    2.10                     py36_0  
> Jinja2                    2.10                      <pip>
> jpeg                      9b                   h024ee3a_2  
> jsonschema                2.6.0                    py36_0  
> jsonschema                2.6.0                     <pip>
> jupyter-client            5.2.3                     <pip>
> jupyter-tensorboard       0.1.8                     <pip>
> jupyter_client            5.2.3                    py36_0  
> jupyter_core              4.4.0                    py36_0  
> keras-applications        1.0.6                    py36_0  
> keras-preprocessing       1.0.5                    py36_0  
> kiwisolver                1.0.1            py36hf484d3e_0  
> libedit                   3.1.20170329         h6b74fdf_2  
> libffi                    3.2.1                hd88cf55_4  
> libgcc-ng                 8.2.0                hdf63c60_1  
> libgfortran-ng            7.3.0                hdf63c60_0  
> libpng                    1.6.35               hbc83047_0  
> libprotobuf               3.6.1                hd408876_0  
> libsodium                 1.0.16               h1bed415_0  
> libstdcxx-ng              8.2.0                hdf63c60_1  
> libuuid                   1.0.3                h1bed415_2  
> libxcb                    1.13                 h1bed415_1  
> libxml2                   2.9.8                h26e45fe_1  
> markdown                  3.0.1                    py36_0  
> MarkupSafe                1.1.0                     <pip>
> markupsafe                1.1.0            py36h7b6447c_0  
> matplotlib                3.0.1            py36h5429711_0  
> mistune                   0.8.4            py36h7b6447c_0  
> mkl                       2018.0.3                      1  
> mkl_fft                   1.0.6            py36h7dd41cf_0  
> mkl_random                1.0.1            py36h4414c95_1  
> nbconvert                 5.3.1                    py36_0  
> nbconvert                 5.4.0                     <pip>
> nbformat                  4.4.0                    py36_0  
> ncurses                   6.1                  hf484d3e_0  
> notebook                  5.7.2                    py36_0  
> numpy                     1.15.4           py36h1d66e8a_0  
> numpy-base                1.15.4           py36h81de0dd_0  
> openssl                   1.0.2p               h14c3975_0  
> pandas                    0.23.4           py36h04863e7_0  
> pandoc                    2.2.3.2                       0  
> pandocfilters             1.4.2                    py36_1  
> parso                     0.3.1                    py36_0  
> patsy                     0.5.1                    py36_0  
> pcre                      8.42                 h439df22_0  
> pexpect                   4.6.0                    py36_0  
> pickleshare               0.7.5                     <pip>
> pickleshare               0.7.5                    py36_0  
> pip                       18.1                     py36_0  
> prometheus-client         0.4.2                     <pip>
> prometheus_client         0.4.2                    py36_0  
> prompt_toolkit            2.0.7                    py36_0  
> protobuf                  3.6.1            py36he6710b0_0  
> ptyprocess                0.6.0                     <pip>
> ptyprocess                0.6.0                    py36_0  
> pygments                  2.2.0                    py36_0  
> Pygments                  2.3.0                     <pip>
> pyparsing                 2.3.0                    py36_0  
> pyqt                      5.9.2            py36h05f1152_2  
> python                    3.6.6                h6e4f718_2  
> python-dateutil           2.7.5                    py36_0  
> pytz                      2018.7                   py36_0  
> pyzmq                     17.1.2           py36h14c3975_0  
> pyzmq                     17.1.2                    <pip>
> qt                        5.9.6                h8703b6f_2  
> readline                  7.0                  h7b6447c_5  
> scipy                     1.1.0            py36hfa4b5c9_1  
> seaborn                   0.9.0                    py36_0  
> Send2Trash                1.5.0                     <pip>
> send2trash                1.5.0                    py36_0  
> setuptools                40.6.2                   py36_0  
> simplejson                3.16.0                    <pip>
> sip                       4.19.8           py36hf484d3e_0  
> six                       1.11.0                   py36_1  
> sqlite                    3.25.3               h7b6447c_0  
> statsmodels               0.9.0            py36h035aef0_0  
> tensorboard               1.12.0           py36hf484d3e_0  
> tensorflow                1.12.0          mkl_py36h69b6ba0_0  
> tensorflow-base           1.12.0          mkl_py36h3c3e929_0  
> termcolor                 1.1.0                    py36_1  
> terminado                 0.8.1                    py36_1  
> terminado                 0.8.1                     <pip>
> testpath                  0.4.2                    py36_0  
> tk                        8.6.8                hbc83047_0  
> tornado                   5.1.1                     <pip>
> tornado                   5.1.1            py36h7b6447c_0  
> traitlets                 4.3.2                    py36_0  
> wcwidth                   0.1.7                    py36_0  
> wcwidth                   0.1.7                     <pip>
> webencodings              0.5.1                    py36_1  
> webencodings              0.5.1                     <pip>
> werkzeug                  0.14.1                   py36_0  
> wheel                     0.32.3                   py36_0  
> xz                        5.2.4                h14c3975_4  
> zeromq                    4.2.5                hf484d3e_1  
> zlib                      1.2.11               h7b6447c_3  
>

**Comment by lspvic** [comment]
It seems you installed the newest tensorflow 1.12 but the this extension supports up to tensorboard 1.11.
Tensorboards API changed almost every version :disappointed_relieved:
I will fix the extension to support tensoflow 1.12 soon.
Thanks for the feedback.

**Comment by tzom** [comment]
yap, my fault.
Thx for such a fast reply.

Downgrading to tensorflow 1.11 is the solution. 
Working like a charm with tf 1.11. Nice plugin, well done!
