### ISSUE TITLE
Launcher Error Invalid response: 500 Internal Server Error

### ISSUE THREAD

**Issue by octavd** [lspvic/jupyter_tensorboard#65]
Hello,

When trying to spawn a new tensorboard i am having the following error ```Launcher Error Invalid response: 500 Internal Server Error```

```

HTTPServerRequest(protocol='http', host='jupyterhub', method='POST', uri='/user/octavd/api/tensorboard?1591806511674', version='HTTP/1.1', remote_ip='::ffff:181.53.9.0')
--
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/tornado/web.py", line 1701, in _execute
  | result = method(*self.path_args, **self.path_kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/tornado/web.py", line 3178, in wrapper
  | return method(self, *args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/jupyter_tensorboard/api_handlers.py", line 40, in post
  | .new_instance(data["logdir"], reload_interval=reload_interval)
  | File "/opt/app-root/lib/python3.6/site-packages/jupyter_tensorboard/tensorboard_manager.py", line 221, in new_instance
  | purge_orphaned_data=purge_orphaned_data)
  | File "/opt/app-root/lib/python3.6/site-packages/jupyter_tensorboard/tensorboard_manager.py", line 47, in create_tb_app
  | tensorboard.assets_zip_provider)
  | File "/opt/app-root/lib/python3.6/site-packages/tensorboard/backend/application.py", line 147, in standard_tensorboard_wsgi
  | flags, plugin_loaders, data_provider, assets_zip_provider, multiplexer
  | File "/opt/app-root/lib/python3.6/site-packages/jupyter_tensorboard/tensorboard_manager.py", line 165, in TensorBoardWSGIApp_2x
  | window_title=flags.window_title)
  | TypeError: __init__() got an unexpected keyword argument 'db_connection_provider'

```
I have the following installed:
```
sh-4.2$ pip list | grep tensor
jupyter-tensorboard    0.2.0      
tensorboard            2.2.2      
tensorboard-plugin-wit 1.6.0.post3
tensorflow             2.2.0      
tensorflow-estimator   2.2.0      
```

Could you please advise how to proceed with this issue?

**Comment by octavd** [comment]
Ok..

I've found a solution to make it work.
I was missing from ```pip``` -> ```tensorboard```

Here you can find the requirements:
```
tensorflow==2.1.0
jupyter-tensorboard==0.2.0
tensorflow-estimator==2.1.0
tensorboard==2.1.0
```
And for ```jupyter```:
```
jupyter-client         6.1.3      
jupyter-core           4.6.3      
jupyter-kernel-gateway 2.4.0      
jupyter-telemetry      0.1.0      
jupyter-tensorboard    0.2.0      
jupyterhub             1.1.0      
jupyterlab             2.1.4         
jupyterlab-server      1.1.5    
```

After adding the missing req it worked like a charm. :)

**Comment by ighack** [comment]
@octavd 

> ighack@ighack-PC:~$ pip list | grep jupyter
> jupyter                            1.0.0
> jupyter-client                     6.1.3
> jupyter-console                    6.1.0
> jupyter-core                       4.6.3
> jupyter-kernel-gateway             2.4.1
> jupyter-telemetry                  0.1.0
> jupyter-tensorboard                0.2.0
> jupyterhub                         1.1.0
> jupyterlab                         2.1.4
> jupyterlab-server                  1.1.5
> 
> ighack@ighack-PC:~$ pip list |grep tensor
> jupyter-tensorboard                0.2.0
> tensorboard                        2.2.2
> tensorboard-plugin-wit             1.6.0.post3
> tensorflow                         2.2.0
> tensorflow-datasets                3.1.0
> tensorflow-estimator               2.2.0
> tensorflow-hub                     0.8.0
> tensorflow-metadata                0.22.2
> tensorflowonspark                  2.2.1
> tensorrt                           6.0.1.5
> 
> 
I aslo get error 

main.min.js?v=7c0e25cc7282dcba9603c595da332685:9837 POST http://127.0.0.1:8888/api/tensorboard 500 (Internal Server Error)
send @ main.min.js?v=7c0e25cc7282dcba9603c595da332685:9837
ajax @ main.min.js?v=7c0e25cc7282dcba9603c595da332685:9434
ajax @ main.min.js?v=7c0e25cc7282dcba9603c595da332685:37145
TensorboardList.new_tensorboard @ tensorboardlist.js?v=20200709101934:143
(anonymous) @ tensorboardlist.js?v=20200709101934:92
proxy @ main.min.js?v=7c0e25cc7282dcba9603c595da332685:10502
dispatch @ main.min.js?v=7c0e25cc7282dcba9603c595da332685:5237
elemData.handle @ main.min.js?v=7c0e25cc7282dcba9603c595da332685:5044
